title: Manoa Clubs Finder
description: Finding Clubs in the UH Community
google_analytics:
show_downloads: false
theme: jekyll-theme-slate
github:
  is_project_page: true
  repository_url: https://github.com/manoa-clubs-finder/manoa-clubs-finder.github.io
gems:
  - jekyll-mentions
